-- TODO: make reusable functions for all weapon types
-- TODO: in the future, instead of functions maybe we will make a folder "weapon" and have modules for shoot, animation et cetera.
-- TODO: the way this work is that each weapon in tool script will have a config dict with with weapon properties such as damage, fire rate,
-- TODO: ammo count, reload time, and so on. The weapon module will then use this config to handle the weapon's behavior.

local module = {}

return module
